### ISSUE TITLE
Waitconditiontimeout for Discovery and Overlord

### ISSUE THREAD

**Issue by v1k0d3n** [ncoghlan/ansible-vagrant-kubernetes#2]
nick, I'm really sorry...I wrote this in the wrong repository! closing my own issue in error!! it's been...one of those days.

**Comment by ncoghlan** [comment]
Heh, edits don't come through via the email notifications, so I was rather confused when reading my tracker notifications. Thanks for the clarification, and I hope you get the problem resolved in the right place :)

**Comment by v1k0d3n** [comment]
yeah, i thought about that saying to myself "this guy's gonna think i've gone mad!". haha great project you have here. i had it open because i'd like to explore using it for a book i'm co-authoring. can we talk about this more over email?
